### ISSUE TITLE
Add a makefile to install and uninstall shup

### ISSUE THREAD

**Issue by calebe94** [pystardust/shup#2]
Hello,

I saw your project on [reddit](https://www.reddit.com/r/suckless/comments/mq4gk2/shup_simple_html_parser_in_sh/).

And I liked it a lot. So I'm using it as a dependency to a project of mine called [tbm](https://github.com/TinyToolSH/tbm) which is a **T**iny **B**ookmark **M**anager.

In the future I intend to package the two projects for Debian and therefore I propose some minor changes to the project. Like adding a makefile to install and uninstall the project.

I will do a PR soon adding the makefile if you allow it.

**Comment by pystardust** [comment]
Sure, feel free to PR. It would be awesome to get it packaged. Any contribution is welcomed
